### ISSUE TITLE
Publish an hex package?

### ISSUE THREAD

**Issue by etnt** [sata/pp_record#2]
Hi,
Have you considered publishing a hex package?
( https://hex.pm/docs/rebar3_publish )

**Comment by sata** [comment]
Hi @etnt, I wasn't aware anyone was using this :).. I can look into it

**Comment by etnt** [comment]
Great! 
I'm using it for the edbg debugger/tracer and wanted to make edbg a hex-package.
But then I need pp_record as a hex package too as a dependency.

**Comment by sata** [comment]
Done. https://hex.pm/packages/pp_record
